[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
rayon = "1.10.0"
regex = "1.11.1"
timed = "0.2.1"
deflate = "1.0.0"

[profile.release]
strip = true
lto = "fat"
panic = "abort"
codegen-units = 1
